import React from "react";
import { worker_icn, worker_icn_2 } from "../assets";

export const workers_staff = [
  {
    id: 1,
    name: "Glauber Mineiro",
    adress: "Av Pirapora, 26",
    birthday: "21/04",
    job: "recepção",
    icon: worker_icn,
    shift: "manhã",
  },
  {
    id: 2,
    name: "Danilo Pereira",
    adress: "Av Matheus Pirao, 2556",
    birthday: "08/11",
    job: "recepção",
    icon: worker_icn,
    shift: "manhã",
  },
  {
    id: 3,
    name: "Mariane Galleano",
    adress: "Rua 14 de Janeiro, 836",
    birthday: "15/08",
    job: "gerente",
    icon: worker_icn_2,
    shift: "tarde",
  },
  {
    id: 4,
    name: "Roger Maturini",
    adress: "Rua Managuira, 9322",
    birthday: "12/09",
    job: "faxineiro",
    icon: worker_icn,
    shift: "noite",
  },
  {
    id: 5,
    name: "Mario Julio Moura",
    adress: "Av Bonfiglioli, 2679",
    birthday: "23/02",
    job: "segurança",
    icon: worker_icn,
    shift: "manhã",
  },
  {
    id: 6,
    name: "Glauber Mineiro",
    adress: "Av Pirapora, 26",
    birthday: "21/10",
    job: "segurança",
    icon: worker_icn,
    shift: "noite",
  },
  {
    id: 7,
    name: "João Burcos",
    adress: "Av Tenente Mineiro, 100",
    birthday: "30/07",
    job: "recepção",
    icon: worker_icn,
    shift: "tarde",
  },
  {
    id: 8,
    name: "Junior Pereira Silva",
    adress: "Av Marcos Aurelio, 56",
    birthday: "02/12",
    job: "recepção",
    icon: worker_icn,
    shift: "tarde",
  },
  {
    id: 9,
    name: "Mateus Cumbú",
    adress: "Av Romeu Filho, 26",
    birthday: "13/12",
    job: "segurança",
    icon: worker_icn,
    shift: "tarde",
  },
];
